name: gitleaks

on:
  push:
  pull_request:

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    container:
      image: zricethezav/gitleaks:latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: gitleaks detect
        run: |
          gitleaks detect \
            --source . \
            --baseline-path .gitleaks-baseline.json \
            --redact \
            --exit-code 1 \
            --verbose
